package jetbrains.mps.samples.Dot.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.editor.runtime.selection.SelectionUtil;
import jetbrains.mps.openapi.editor.selection.SelectionManager;

public class Graph_Strict_Flags {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.DELETE, new Graph_Strict_Flags.Graph_Strict_Flags_DELETE(node));
    editorCell.setAction(CellActionType.BACKSPACE, new Graph_Strict_Flags.Graph_Strict_Flags_BACKSPACE(node));
  }
  public static class Graph_Strict_Flags_DELETE extends AbstractCellAction {
    /*package*/ SNode myNode;
    public Graph_Strict_Flags_DELETE(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65acL, 0x3881fc82f19d65d7L, "strict"), "" + (false));
      SelectionUtil.selectCell(editorContext, node, SelectionManager.FIRST_CELL);
    }
  }
  public static class Graph_Strict_Flags_BACKSPACE extends AbstractCellAction {
    /*package*/ SNode myNode;
    public Graph_Strict_Flags_BACKSPACE(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65acL, 0x3881fc82f19d65d7L, "strict"), "" + (false));
      SelectionUtil.selectCell(editorContext, node, SelectionManager.FIRST_CELL);
    }
  }
}
