package jetbrains.mps.samples.Dot.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;

public class Compass_pt_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    String testValue = null;
    if (value == null) {
      testValue = "";
    } else {
      testValue = value;
    }
    return testValue.matches("(n|ne|e|se|s|sw|w|nw|c|)");
  }
}
