package jetbrains.mps.samples.Dot.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;

public class ID_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    String testValue = null;
    if (value == null) {
      testValue = "";
    } else {
      testValue = value;
    }
    return testValue.matches("(0|[\\-]?[1-9]([0-9])*|[a-zA-Z\200-\3770-9]*)");
  }
}
