package jetbrains.mps.samples.Dot.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.concept.SConceptAdapterById;
import jetbrains.mps.smodel.adapter.structure.concept.SInterfaceConceptAdapterById;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.SNodePointer;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  private final Map<SConceptId, Integer> myIndexMap = new HashMap<SConceptId, Integer>(29);
  /*package*/ final ConceptDescriptor myConceptA_list = createDescriptorForA_list();
  /*package*/ final ConceptDescriptor myConceptAttr_list = createDescriptorForAttr_list();
  /*package*/ final ConceptDescriptor myConceptAttr_stmt = createDescriptorForAttr_stmt();
  /*package*/ final ConceptDescriptor myConceptBaseConcept = createDescriptorForBaseConcept();
  /*package*/ final ConceptDescriptor myConceptEdgeRHS = createDescriptorForEdgeRHS();
  /*package*/ final ConceptDescriptor myConceptEdgeRHS_block_1_1_1 = createDescriptorForEdgeRHS_block_1_1_1();
  /*package*/ final ConceptDescriptor myConceptEdgeRHS_block_1_1_2 = createDescriptorForEdgeRHS_block_1_1_2();
  /*package*/ final ConceptDescriptor myConceptEdge_stmt = createDescriptorForEdge_stmt();
  /*package*/ final ConceptDescriptor myConceptEdge_stmt_block_1_1_1 = createDescriptorForEdge_stmt_block_1_1_1();
  /*package*/ final ConceptDescriptor myConceptEdge_stmt_block_1_1_2 = createDescriptorForEdge_stmt_block_1_1_2();
  /*package*/ final ConceptDescriptor myConceptGraph = createDescriptorForGraph();
  /*package*/ final ConceptDescriptor myConceptIEdgeRHS_block_1_1 = createDescriptorForIEdgeRHS_block_1_1();
  /*package*/ final ConceptDescriptor myConceptIEdge_stmt_block_1_1 = createDescriptorForIEdge_stmt_block_1_1();
  /*package*/ final ConceptDescriptor myConceptIPort = createDescriptorForIPort();
  /*package*/ final ConceptDescriptor myConceptIStmt = createDescriptorForIStmt();
  /*package*/ final ConceptDescriptor myConceptIdentifiableConcept = createDescriptorForIdentifiableConcept();
  /*package*/ final ConceptDescriptor myConceptNode_id = createDescriptorForNode_id();
  /*package*/ final ConceptDescriptor myConceptNode_stmt = createDescriptorForNode_stmt();
  /*package*/ final ConceptDescriptor myConceptPort_1 = createDescriptorForPort_1();
  /*package*/ final ConceptDescriptor myConceptPort_2 = createDescriptorForPort_2();
  /*package*/ final ConceptDescriptor myConceptStmt_1 = createDescriptorForStmt_1();
  /*package*/ final ConceptDescriptor myConceptStmt_2 = createDescriptorForStmt_2();
  /*package*/ final ConceptDescriptor myConceptStmt_3 = createDescriptorForStmt_3();
  /*package*/ final ConceptDescriptor myConceptStmt_4 = createDescriptorForStmt_4();
  /*package*/ final ConceptDescriptor myConceptStmt_5 = createDescriptorForStmt_5();
  /*package*/ final ConceptDescriptor myConceptStmt_list = createDescriptorForStmt_list();
  /*package*/ final ConceptDescriptor myConceptStmt_list_block_1_1 = createDescriptorForStmt_list_block_1_1();
  /*package*/ final ConceptDescriptor myConceptSubgraph = createDescriptorForSubgraph();
  /*package*/ final ConceptDescriptor myConceptSubgraph_block_1_1 = createDescriptorForSubgraph_block_1_1();

  public StructureAspectDescriptor() {
    myIndexMap.put(myConceptA_list.getId(), 0);
    myIndexMap.put(myConceptAttr_list.getId(), 1);
    myIndexMap.put(myConceptAttr_stmt.getId(), 2);
    myIndexMap.put(myConceptBaseConcept.getId(), 3);
    myIndexMap.put(myConceptEdgeRHS.getId(), 4);
    myIndexMap.put(myConceptEdgeRHS_block_1_1_1.getId(), 5);
    myIndexMap.put(myConceptEdgeRHS_block_1_1_2.getId(), 6);
    myIndexMap.put(myConceptEdge_stmt.getId(), 7);
    myIndexMap.put(myConceptEdge_stmt_block_1_1_1.getId(), 8);
    myIndexMap.put(myConceptEdge_stmt_block_1_1_2.getId(), 9);
    myIndexMap.put(myConceptGraph.getId(), 10);
    myIndexMap.put(myConceptIEdgeRHS_block_1_1.getId(), 11);
    myIndexMap.put(myConceptIEdge_stmt_block_1_1.getId(), 12);
    myIndexMap.put(myConceptIPort.getId(), 13);
    myIndexMap.put(myConceptIStmt.getId(), 14);
    myIndexMap.put(myConceptIdentifiableConcept.getId(), 15);
    myIndexMap.put(myConceptNode_id.getId(), 16);
    myIndexMap.put(myConceptNode_stmt.getId(), 17);
    myIndexMap.put(myConceptPort_1.getId(), 18);
    myIndexMap.put(myConceptPort_2.getId(), 19);
    myIndexMap.put(myConceptStmt_1.getId(), 20);
    myIndexMap.put(myConceptStmt_2.getId(), 21);
    myIndexMap.put(myConceptStmt_3.getId(), 22);
    myIndexMap.put(myConceptStmt_4.getId(), 23);
    myIndexMap.put(myConceptStmt_5.getId(), 24);
    myIndexMap.put(myConceptStmt_list.getId(), 25);
    myIndexMap.put(myConceptStmt_list_block_1_1.getId(), 26);
    myIndexMap.put(myConceptSubgraph.getId(), 27);
    myIndexMap.put(myConceptSubgraph_block_1_1.getId(), 28);
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptA_list, myConceptAttr_list, myConceptAttr_stmt, myConceptBaseConcept, myConceptEdgeRHS, myConceptEdgeRHS_block_1_1_1, myConceptEdgeRHS_block_1_1_2, myConceptEdge_stmt, myConceptEdge_stmt_block_1_1_1, myConceptEdge_stmt_block_1_1_2, myConceptGraph, myConceptIEdgeRHS_block_1_1, myConceptIEdge_stmt_block_1_1, myConceptIPort, myConceptIStmt, myConceptIdentifiableConcept, myConceptNode_id, myConceptNode_stmt, myConceptPort_1, myConceptPort_2, myConceptStmt_1, myConceptStmt_2, myConceptStmt_3, myConceptStmt_4, myConceptStmt_5, myConceptStmt_list, myConceptStmt_list_block_1_1, myConceptSubgraph, myConceptSubgraph_block_1_1);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    Integer index = myIndexMap.get(id);
    if (index == null) {
      return null;
    }
    switch (((int) index)) {
      case 0:
        return myConceptA_list;
      case 1:
        return myConceptAttr_list;
      case 2:
        return myConceptAttr_stmt;
      case 3:
        return myConceptBaseConcept;
      case 4:
        return myConceptEdgeRHS;
      case 5:
        return myConceptEdgeRHS_block_1_1_1;
      case 6:
        return myConceptEdgeRHS_block_1_1_2;
      case 7:
        return myConceptEdge_stmt;
      case 8:
        return myConceptEdge_stmt_block_1_1_1;
      case 9:
        return myConceptEdge_stmt_block_1_1_2;
      case 10:
        return myConceptGraph;
      case 11:
        return myConceptIEdgeRHS_block_1_1;
      case 12:
        return myConceptIEdge_stmt_block_1_1;
      case 13:
        return myConceptIPort;
      case 14:
        return myConceptIStmt;
      case 15:
        return myConceptIdentifiableConcept;
      case 16:
        return myConceptNode_id;
      case 17:
        return myConceptNode_stmt;
      case 18:
        return myConceptPort_1;
      case 19:
        return myConceptPort_2;
      case 20:
        return myConceptStmt_1;
      case 21:
        return myConceptStmt_2;
      case 22:
        return myConceptStmt_3;
      case 23:
        return myConceptStmt_4;
      case 24:
        return myConceptStmt_5;
      case 25:
        return myConceptStmt_list;
      case 26:
        return myConceptStmt_list_block_1_1;
      case 27:
        return myConceptSubgraph;
      case 28:
        return myConceptSubgraph_block_1_1;
      default:
        throw new IllegalStateException();
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    Integer res = null;
    if (c instanceof SConceptAdapterById) {
      res = myIndexMap.get(((SConceptAdapterById) c).getId());
    } else if (c instanceof SInterfaceConceptAdapterById) {
      res = myIndexMap.get(((SInterfaceConceptAdapterById) c).getId());
    }
    return (res == null ? -1 : res);
  }

  private static ConceptDescriptor createDescriptorForA_list() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.A_list", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659dL)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65b9L, "ID_1", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211321")), new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65baL, "ID_2", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211322")), new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65bcL, "Attr_separator_3", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211324"))).properties("ID_1", "ID_2", "Attr_separator_3").childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65bdL, "A_list_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659dL), true, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211325"))).children(new String[]{"A_list_1"}, new boolean[]{false}).alias("=", "A_list").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211293")).create();
  }
  private static ConceptDescriptor createDescriptorForAttr_list() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Attr_list", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659eL)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65beL, "A_list_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659dL), true, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211326")), new ConceptDescriptorBuilder.Link(0x3881fc82f19d65bfL, "Attr_list_2", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659eL), true, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211327"))).children(new String[]{"A_list_1", "Attr_list_2"}, new boolean[]{false, false}).alias("[ ]", "Attr_list").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211294")).create();
  }
  private static ConceptDescriptor createDescriptorForAttr_stmt() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Attr_stmt", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a2L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept", "jetbrains.mps.samples.Dot.structure.IStmt").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b1L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65c3L, "Attr_target_1", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211331"))).properties("Attr_target_1").childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65c4L, "Attr_list_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659eL), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211332"))).children(new String[]{"Attr_list_1"}, new boolean[]{false}).alias("Attr_stmt", "Attr_stmt").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211298")).create();
  }
  private static ConceptDescriptor createDescriptorForBaseConcept() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.BaseConcept", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).abstract_().sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211292")).create();
  }
  private static ConceptDescriptor createDescriptorForEdgeRHS() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.EdgeRHS", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a3L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65c6L, "Edgeop_1", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211334"))).properties("Edgeop_1").childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65c7L, "EdgeRHS_block_1_1_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659fL), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211335")), new ConceptDescriptorBuilder.Link(0x3881fc82f19d65c8L, "EdgeRHS_2", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a3L), true, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211336"))).children(new String[]{"EdgeRHS_block_1_1_1", "EdgeRHS_2"}, new boolean[]{false, false}).alias("EdgeRHS", "EdgeRHS").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211299")).create();
  }
  private static ConceptDescriptor createDescriptorForEdgeRHS_block_1_1_1() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.EdgeRHS_block_1_1_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a0L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65c0L, "Node_id_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b7L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211328"))).children(new String[]{"Node_id_1"}, new boolean[]{false}).alias("Node_id", "EdgeRHS_block_1_1").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211296")).create();
  }
  private static ConceptDescriptor createDescriptorForEdgeRHS_block_1_1_2() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.EdgeRHS_block_1_1_2", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a1L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65c1L, "Subgraph_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b0L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211329"))).children(new String[]{"Subgraph_1"}, new boolean[]{false}).alias("Subgraph", "EdgeRHS_block_1_1").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211297")).create();
  }
  private static ConceptDescriptor createDescriptorForEdge_stmt() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Edge_stmt", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a8L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept", "jetbrains.mps.samples.Dot.structure.IStmt").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b1L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65d1L, "Edge_stmt_block_1_1_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a9L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211345")), new ConceptDescriptorBuilder.Link(0x3881fc82f19d65d2L, "EdgeRHS_2", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a3L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211346")), new ConceptDescriptorBuilder.Link(0x3881fc82f19d65d3L, "Attr_list_3", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659eL), true, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211347"))).children(new String[]{"Edge_stmt_block_1_1_1", "EdgeRHS_2", "Attr_list_3"}, new boolean[]{false, false, false}).alias("Edge_stmt", "Edge_stmt").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211304")).create();
  }
  private static ConceptDescriptor createDescriptorForEdge_stmt_block_1_1_1() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Edge_stmt_block_1_1_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65aaL)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65d4L, "Node_id_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b7L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211348"))).children(new String[]{"Node_id_1"}, new boolean[]{false}).alias("Node_id", "Edge_stmt_block_1_1").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211306")).create();
  }
  private static ConceptDescriptor createDescriptorForEdge_stmt_block_1_1_2() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Edge_stmt_block_1_1_2", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65abL)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65d5L, "Subgraph_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b0L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211349"))).children(new String[]{"Subgraph_1"}, new boolean[]{false}).alias("Subgraph", "Edge_stmt_block_1_1").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211307")).create();
  }
  private static ConceptDescriptor createDescriptorForGraph() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Graph", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65acL)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept", "jetbrains.mps.samples.Dot.structure.IdentifiableConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19e725cL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65d7L, "strict", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211351")), new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65d9L, "graphKind", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211353"))).properties("strict", "graphKind").childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65dbL, "Stmt_list_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a5L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211355"))).children(new String[]{"Stmt_list_1"}, new boolean[]{false}).rootable().alias("{ }", "Graph").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211308")).create();
  }
  private static ConceptDescriptor createDescriptorForIEdgeRHS_block_1_1() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.IEdgeRHS_block_1_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659fL)).version(1).interface_().sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211295")).create();
  }
  private static ConceptDescriptor createDescriptorForIEdge_stmt_block_1_1() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.IEdge_stmt_block_1_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a9L)).version(1).interface_().sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211305")).create();
  }
  private static ConceptDescriptor createDescriptorForIPort() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.IPort", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65adL)).version(1).interface_().sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211309")).create();
  }
  private static ConceptDescriptor createDescriptorForIStmt() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.IStmt", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b1L)).version(1).interface_().sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211313")).create();
  }
  private static ConceptDescriptor createDescriptorForIdentifiableConcept() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.IdentifiableConcept", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19e725cL)).version(1).interface_().parents("jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449280092")).create();
  }
  private static ConceptDescriptor createDescriptorForNode_id() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Node_id", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b7L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept", "jetbrains.mps.samples.Dot.structure.IEdgeRHS_block_1_1", "jetbrains.mps.samples.Dot.structure.IEdge_stmt_block_1_1").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659fL), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a9L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65e8L, "ID_1", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211368"))).properties("ID_1").childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65e9L, "Port_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65adL), true, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211369"))).children(new String[]{"Port_1"}, new boolean[]{false}).alias("Node_id", "Node_id").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211319")).create();
  }
  private static ConceptDescriptor createDescriptorForNode_stmt() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Node_stmt", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a7L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept", "jetbrains.mps.samples.Dot.structure.IStmt").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b1L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65cfL, "Node_id_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b7L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211343")), new ConceptDescriptorBuilder.Link(0x3881fc82f19d65d0L, "Attr_list_2", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659eL), true, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211344"))).children(new String[]{"Node_id_1", "Attr_list_2"}, new boolean[]{false, false}).alias("Node_stmt", "Node_stmt").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211303")).create();
  }
  private static ConceptDescriptor createDescriptorForPort_1() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Port_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65aeL)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept", "jetbrains.mps.samples.Dot.structure.IPort").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65adL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65dcL, "ID_1", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211356")), new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65deL, "Compass_pt_2", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211358"))).properties("ID_1", "Compass_pt_2").alias(": :", "Port").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211310")).create();
  }
  private static ConceptDescriptor createDescriptorForPort_2() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Port_2", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65afL)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept", "jetbrains.mps.samples.Dot.structure.IPort").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65adL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65dfL, "Compass_pt_1", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211359"))).properties("Compass_pt_1").alias(":", "Port").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211311")).create();
  }
  private static ConceptDescriptor createDescriptorForStmt_1() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Stmt_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b2L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65e2L, "Node_stmt_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a7L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211362"))).children(new String[]{"Node_stmt_1"}, new boolean[]{false}).alias("Node_stmt stmt", "Stmt").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211314")).create();
  }
  private static ConceptDescriptor createDescriptorForStmt_2() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Stmt_2", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b3L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65e3L, "Edge_stmt_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a8L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211363"))).children(new String[]{"Edge_stmt_1"}, new boolean[]{false}).alias("Edge_stmt stmt", "Stmt").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211315")).create();
  }
  private static ConceptDescriptor createDescriptorForStmt_3() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Stmt_3", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b4L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65e4L, "Attr_stmt_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a2L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211364"))).children(new String[]{"Attr_stmt_1"}, new boolean[]{false}).alias("Attr_stmt stmt", "Stmt").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211316")).create();
  }
  private static ConceptDescriptor createDescriptorForStmt_4() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Stmt_4", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b5L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept", "jetbrains.mps.samples.Dot.structure.IStmt").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b1L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65e5L, "ID_1", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211365")), new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65e6L, "ID_2", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211366"))).properties("ID_1", "ID_2").alias("=", "Stmt").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211317")).create();
  }
  private static ConceptDescriptor createDescriptorForStmt_5() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Stmt_5", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b6L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65e7L, "Subgraph_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b0L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211367"))).children(new String[]{"Subgraph_1"}, new boolean[]{false}).alias("Subgraph stmt", "Stmt").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211318")).create();
  }
  private static ConceptDescriptor createDescriptorForStmt_list() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Stmt_list", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a5L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65cbL, "Stmt_list_block_1_1_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a4L), true, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211339"))).children(new String[]{"Stmt_list_block_1_1_1"}, new boolean[]{false}).alias("Stmt_list_block_1_1 stmt_list", "Stmt_list").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211301")).create();
  }
  private static ConceptDescriptor createDescriptorForStmt_list_block_1_1() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Stmt_list_block_1_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a4L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65c9L, "Stmt_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b1L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211337")), new ConceptDescriptorBuilder.Link(0x3881fc82f19d65caL, "Stmt_list_2", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a5L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211338"))).children(new String[]{"Stmt_1", "Stmt_list_2"}, new boolean[]{false, false}).alias(";", "Stmt_list_block_1_1").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211300")).create();
  }
  private static ConceptDescriptor createDescriptorForSubgraph() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Subgraph", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b0L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept", "jetbrains.mps.samples.Dot.structure.IStmt", "jetbrains.mps.samples.Dot.structure.IEdgeRHS_block_1_1", "jetbrains.mps.samples.Dot.structure.IEdge_stmt_block_1_1").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65b1L), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659fL), MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a9L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x3881fc82f19d65e0L, "Subgraph_block_1_1_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a6L), true, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211360")), new ConceptDescriptorBuilder.Link(0x3881fc82f19d65e1L, "Stmt_list_2", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a5L), false, false, false, new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211361"))).children(new String[]{"Subgraph_block_1_1_1", "Stmt_list_2"}, new boolean[]{false, false}).alias("{ }", "Subgraph").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211312")).create();
  }
  private static ConceptDescriptor createDescriptorForSubgraph_block_1_1() {
    return new ConceptDescriptorBuilder("jetbrains.mps.samples.Dot.structure.Subgraph_block_1_1", MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d65a6L)).super_("jetbrains.mps.samples.Dot.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).parents("jetbrains.mps.samples.Dot.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xfb046105bd7c48d7L, 0xbb7b88a9914e3cc3L, 0x3881fc82f19d659cL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65cdL, "Subgraph_0DCm_1", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211341")), new ConceptDescriptorBuilder.Prop(0x3881fc82f19d65ceL, "ID_2", new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211342"))).properties("Subgraph_0DCm_1", "ID_2").alias("Subgraph_block_1_1", "Subgraph_block_1_1").sourceNode(new SNodePointer("r:12c82f07-44c4-4d22-9a27-3ace56e28889(jetbrains.mps.samples.Dot.structure)", "4071813177449211302")).create();
  }
}
